### ISSUE TITLE
Create Obstacles

### ISSUE THREAD

**Issue by wpowell-se** [Ckeds/Runner_Team_FC#3]

**Comment by MysterMee** [comment]
Find/Create Models for above
https://www.assetstore.unity3d.com/en/#!/content/54622 (Tree)
https://www.assetstore.unity3d.com/en/#!/content/29170 (Tree)
https://www.assetstore.unity3d.com/en/#!/content/53146 (Rock)
https://www.assetstore.unity3d.com/en/#!/content/2452 (Rocks)
https://www.assetstore.unity3d.com/en/#!/content/13168 (Bushes)
https://www.assetstore.unity3d.com/en/#!/content/13392 (Foliage)
https://www.assetstore.unity3d.com/en/#!/content/49089 (Fallen Log)
https://www.assetstore.unity3d.com/en/#!/content/6236 (Stone Wall)
https://www.assetstore.unity3d.com/en/#!/content/49221 (Park Bench/Lamp)
https://www.assetstore.unity3d.com/en/#!/content/850 (Park Bench)
https://www.assetstore.unity3d.com/en/#!/content/652 (Park Barricade)
https://www.assetstore.unity3d.com/en/#!/content/23183 (Trash Can)
